### ISSUE TITLE
dataset url is  403 Forbidden

### ISSUE THREAD

**Issue by shufangxun** [m-bain/webvid#1]
dataset url is  403 Forbidden, do you have any idea to solve it, thx!

**Comment by m-bain** [comment]
Are you getting this on every video? I haven't got this before, its possibly IP blocking

**Comment by Noyii** [comment]
Here are all the invalid videoids: [10681772, 3741062, 6315860, 3742148, 4422923, 2416907, 3742151, 7412620]
