### ISSUE TITLE
some records of this two csv show NaN in ‘page_dir’ field

### ISSUE THREAD

**Issue by realTaki** [m-bain/webvid#2]
does it right? or does something bad happen when I download these CSV files?

**Comment by m-bain** [comment]
Ah yes, good find, I checked and theres 367 of these in the train csv file. Nan 'page_dir' means I failed to download them and they were not saved in a a page subdirectory. You can ignore these, i'll update the csv's with them removed soon.

If you write me an email I can give you a fast download script

**Comment by mzolfaghari** [comment]
Hi @m-bain, can you please share the script for downloading the dataset? my email is: zolfagha@cs.uni-freiburg.de. thanks
