### ISSUE TITLE
results_2M_val.csv download is closed，how to get it

### ISSUE THREAD

**Issue by magicwang1111** [m-bain/webvid#21]
(base) [wangxi@v100-4 webvid]$ wget -nc http://www.robots.ox.ac.uk/~maxbain/webvid/results_2M_val.csv
--2024-02-27 10:49:36--  http://www.robots.ox.ac.uk/~maxbain/webvid/results_2M_val.csv
Resolving www.robots.ox.ac.uk (www.robots.ox.ac.uk)... 129.67.94.2
Connecting to www.robots.ox.ac.uk (www.robots.ox.ac.uk)|129.67.94.2|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.robots.ox.ac.uk/~maxbain/webvid/results_2M_val.csv [following]
--2024-02-27 10:49:43--  https://www.robots.ox.ac.uk/~maxbain/webvid/results_2M_val.csv
Connecting to www.robots.ox.ac.uk (www.robots.ox.ac.uk)|129.67.94.2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-02-27 10:49:44 ERROR 404: Not Found.

(base) [wangxi@v100-4 webvid]$

**Comment by shutterstock-is-cringe** [comment]
Webvid2M:

- Train: https://anon-datasets.s3.amazonaws.com/results_2M_train.csv

- Val: https://anon-datasets.s3.amazonaws.com/results_2M_val.csv



Webvid10M

- Train: https://anon-datasets.s3.amazonaws.com/results_10M_train.csv

- Val: https://anon-datasets.s3.amazonaws.com/results_10M_val.csv

**Comment by magicwang1111** [comment]
> Webvid2M:
> 
> * Train: https://anon-datasets.s3.amazonaws.com/results_2M_train.csv
> * Val: https://anon-datasets.s3.amazonaws.com/results_2M_val.csv
> 
> Webvid10M
> 
> * Train: https://anon-datasets.s3.amazonaws.com/results_10M_train.csv
> * Val: https://anon-datasets.s3.amazonaws.com/results_10M_val.csv

Webvid10M LINK CAN'T USE.

**Comment by jayhsu0627** [comment]
[Webvid10M](https://anon-datasets.s3.amazonaws.com/results_10M_val.csv) LINK CAN'T USE

**Comment by wongtou** [comment]
> [Webvid10M](https://anon-datasets.s3.amazonaws.com/results_10M_val.csv) LINK CAN'T USE

https://hyper.ai/en/datasets/17289

**Comment by wongtou** [comment]
> [Webvid10M](https://anon-datasets.s3.amazonaws.com/results_10M_val.csv) LINK CAN'T USE

https://hyper.ai/en/datasets/17289
