### ISSUE TITLE
About the correlation between 2.5m subset and 10m dataset.

### ISSUE THREAD

**Issue by YTEP-ZHI** [m-bain/webvid#23]
Hi @m-bain, I'm wondering whether the csv file of 2.5m subset is **DIRECTLY** sampled from the complete 10m csv file, meaning that the _videoid_ and _page_dir_ should be identical for the same video in both csv files (10m and 2.5m version) without other ordering issues?

**Comment by m-bain** [comment]
Correct yes

**Comment by YTEP-ZHI** [comment]
@m-bain Thanks for your reply. I will this the issue.
