### ISSUE TITLE
Script to download the videos

### ISSUE THREAD

**Issue by bryant1410** [m-bain/webvid#4]
Just saw you released a download script. FWIW, this is what I used to download the 2M version, just wanted to share it. I think it's simpler (it uses csvkit and `parallel`) but maybe it has fewer features:

```bash
csvcut -c videoid,contentUrl results_2M_val.csv \
  | sed 1d \
  | parallel --resume -v --joblog val.log --bar -j 8 'video_id=$(echo {} | cut -d , -f 1) && url=$(echo {} | cut -d , -f 2) && extension=${url##*.} && wget --no-clobber -qO "videos/val/$video_id.$extension" $url'
```

It downloads with 8 jobs in parallel (the flag `-j 8`).

**Comment by bryant1410** [comment]
I'm closing this cause it's not an actual issue but something I just wanted to share.

**Comment by bryant1410** [comment]
Btw, happy to see a script was shared! Simplifies users' lifes

**Comment by m-bain** [comment]
Yeah I think my way is defo not the simplest or the fastest :') -- yours is a neat one liner. Im looking into img2dataset atm too.

**Comment by bryant1410** [comment]
Yeah, I saw you shared img2dataset. Sounds interesting for starting without even pre-downloading the dataset!

**Comment by RyanMarten** [comment]
@bryant1410 @m-bain I used your script and scaled it to run simultaneously on 1,000 VMs in a GCP batch job: 
https://github.com/RyanMarten/distributed_gcp_youtube_download
Downloads WebVid10m in 10 minutes

**Comment by jiaxiangc** [comment]
> Yeah, I saw you shared img2dataset. Sounds interesting for starting without even pre-downloading the dataset!

Thanks your contribution for quickly downloading videos.
