### ISSUE TITLE
Questions about the dataset storage.

### ISSUE THREAD

**Issue by HenryHZY** [m-bain/webvid#7]
Hi @m-bain 
1. How large are the WebVid2.5M and WebVid10M respectively? If it is convenient, please show video-storage and text-storage.
2. Have you finished pretraining FIT (or other model) on WebVid10M? If yes, how long does it take?

**Comment by m-bain** [comment]
Hi,

Text storage (csv files) sizes are shown in the readme.

Default resolution for videos is 5TB and 20TB for webvid 2.5M and 10M respectively.

Best,
Max
