### ISSUE TITLE
Question about the page_dir.

### ISSUE THREAD

**Issue by HenryHZY** [m-bain/webvid#8]
Hi @m-bain 
I have downloaded the webvid10M_val by your ‘results_10M_val.csv’ and 'download.py'. I would like to ask some questions about the page_dir.

1. How do you produce the page_dir for each videoid? 
Just like videoid%10?

2. What is the function of page_dir? 
To avoid the limitation of the maximum number of files per directory?

3. What file order should I use for pre-training? 
Follow the page_dir from small to big?
Follow the results_10M_train.csv from the first row to the last row?

Thank you:)

**Comment by m-bain** [comment]
Hi sorry I missed this.

1. Page_dir indicates the page the video was scraped on (typically 200 per page I think).
2.  Yes to avoid too many files per directory, many file systems discourage > 10K files per directory
3. Pretraining order should be random
